name: Automatic Testing for Resource Management Web App

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub Repo
        uses: actions/checkout@v3

      - name: Setup Node.js in Ubuntu
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Add Node.js version 20 to the test job
          cache: 'npm'

      - name: Remove existing node_modules folder from cloned project
        run: rm -rf /home/runner/work/resource-mgmt/resource-mgmt/node_modules/*

      - name: Install dependencies based on package.json
        run: npm install

      - name: Run tests in "tests" folder
        run: npm test

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20]  # Add Node.js version 20 to the build matrix

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
